// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/passenger/passenger.proto

package passenger

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPassengerProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PassengerId   string                 `protobuf:"bytes,1,opt,name=passenger_id,json=passengerId,proto3" json:"passenger_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPassengerProfileRequest) Reset() {
	*x = GetPassengerProfileRequest{}
	mi := &file_proto_passenger_passenger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPassengerProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPassengerProfileRequest) ProtoMessage() {}

func (x *GetPassengerProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_passenger_passenger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPassengerProfileRequest.ProtoReflect.Descriptor instead.
func (*GetPassengerProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_passenger_passenger_proto_rawDescGZIP(), []int{0}
}

func (x *GetPassengerProfileRequest) GetPassengerId() string {
	if x != nil {
		return x.PassengerId
	}
	return ""
}

type GetPassengerProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Rating        float64                `protobuf:"fixed64,3,opt,name=rating,proto3" json:"rating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPassengerProfileResponse) Reset() {
	*x = GetPassengerProfileResponse{}
	mi := &file_proto_passenger_passenger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPassengerProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPassengerProfileResponse) ProtoMessage() {}

func (x *GetPassengerProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_passenger_passenger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPassengerProfileResponse.ProtoReflect.Descriptor instead.
func (*GetPassengerProfileResponse) Descriptor() ([]byte, []int) {
	return file_proto_passenger_passenger_proto_rawDescGZIP(), []int{1}
}

func (x *GetPassengerProfileResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetPassengerProfileResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetPassengerProfileResponse) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

var File_proto_passenger_passenger_proto protoreflect.FileDescriptor

const file_proto_passenger_passenger_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/passenger/passenger.proto\x12\tpassenger\"?\n" +
	"\x1aGetPassengerProfileRequest\x12!\n" +
	"\fpassenger_id\x18\x01 \x01(\tR\vpassengerId\"_\n" +
	"\x1bGetPassengerProfileResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x16\n" +
	"\x06rating\x18\x03 \x01(\x01R\x06rating2x\n" +
	"\x10PassengerService\x12d\n" +
	"\x13GetPassengerProfile\x12%.passenger.GetPassengerProfileRequest\x1a&.passenger.GetPassengerProfileResponseB4Z2github.com/ngthluu/miniuber/common/proto/passengerb\x06proto3"

var (
	file_proto_passenger_passenger_proto_rawDescOnce sync.Once
	file_proto_passenger_passenger_proto_rawDescData []byte
)

func file_proto_passenger_passenger_proto_rawDescGZIP() []byte {
	file_proto_passenger_passenger_proto_rawDescOnce.Do(func() {
		file_proto_passenger_passenger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_passenger_passenger_proto_rawDesc), len(file_proto_passenger_passenger_proto_rawDesc)))
	})
	return file_proto_passenger_passenger_proto_rawDescData
}

var file_proto_passenger_passenger_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_passenger_passenger_proto_goTypes = []any{
	(*GetPassengerProfileRequest)(nil),  // 0: passenger.GetPassengerProfileRequest
	(*GetPassengerProfileResponse)(nil), // 1: passenger.GetPassengerProfileResponse
}
var file_proto_passenger_passenger_proto_depIdxs = []int32{
	0, // 0: passenger.PassengerService.GetPassengerProfile:input_type -> passenger.GetPassengerProfileRequest
	1, // 1: passenger.PassengerService.GetPassengerProfile:output_type -> passenger.GetPassengerProfileResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_passenger_passenger_proto_init() }
func file_proto_passenger_passenger_proto_init() {
	if File_proto_passenger_passenger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_passenger_passenger_proto_rawDesc), len(file_proto_passenger_passenger_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_passenger_passenger_proto_goTypes,
		DependencyIndexes: file_proto_passenger_passenger_proto_depIdxs,
		MessageInfos:      file_proto_passenger_passenger_proto_msgTypes,
	}.Build()
	File_proto_passenger_passenger_proto = out.File
	file_proto_passenger_passenger_proto_goTypes = nil
	file_proto_passenger_passenger_proto_depIdxs = nil
}
