// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/ride/ride.proto

package ride

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RideStatus int32

const (
	RideStatus_UNKNOWN   RideStatus = 0
	RideStatus_CREATED   RideStatus = 1
	RideStatus_MATCHED   RideStatus = 2
	RideStatus_STARTED   RideStatus = 3
	RideStatus_COMPLETED RideStatus = 4
	RideStatus_CANCELLED RideStatus = 5
)

// Enum value maps for RideStatus.
var (
	RideStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "CREATED",
		2: "MATCHED",
		3: "STARTED",
		4: "COMPLETED",
		5: "CANCELLED",
	}
	RideStatus_value = map[string]int32{
		"UNKNOWN":   0,
		"CREATED":   1,
		"MATCHED":   2,
		"STARTED":   3,
		"COMPLETED": 4,
		"CANCELLED": 5,
	}
)

func (x RideStatus) Enum() *RideStatus {
	p := new(RideStatus)
	*p = x
	return p
}

func (x RideStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RideStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_ride_ride_proto_enumTypes[0].Descriptor()
}

func (RideStatus) Type() protoreflect.EnumType {
	return &file_proto_ride_ride_proto_enumTypes[0]
}

func (x RideStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RideStatus.Descriptor instead.
func (RideStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_ride_ride_proto_rawDescGZIP(), []int{0}
}

type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_proto_ride_ride_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ride_ride_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_proto_ride_ride_proto_rawDescGZIP(), []int{0}
}

func (x *Location) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Location) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type CreateRideRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PassengerId     string                 `protobuf:"bytes,1,opt,name=passenger_id,json=passengerId,proto3" json:"passenger_id,omitempty"`
	PickupLocation  *Location              `protobuf:"bytes,2,opt,name=pickup_location,json=pickupLocation,proto3" json:"pickup_location,omitempty"`
	DropoffLocation *Location              `protobuf:"bytes,3,opt,name=dropoff_location,json=dropoffLocation,proto3" json:"dropoff_location,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateRideRequest) Reset() {
	*x = CreateRideRequest{}
	mi := &file_proto_ride_ride_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRideRequest) ProtoMessage() {}

func (x *CreateRideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ride_ride_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRideRequest.ProtoReflect.Descriptor instead.
func (*CreateRideRequest) Descriptor() ([]byte, []int) {
	return file_proto_ride_ride_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRideRequest) GetPassengerId() string {
	if x != nil {
		return x.PassengerId
	}
	return ""
}

func (x *CreateRideRequest) GetPickupLocation() *Location {
	if x != nil {
		return x.PickupLocation
	}
	return nil
}

func (x *CreateRideRequest) GetDropoffLocation() *Location {
	if x != nil {
		return x.DropoffLocation
	}
	return nil
}

type CreateRideResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RideId        string                 `protobuf:"bytes,1,opt,name=ride_id,json=rideId,proto3" json:"ride_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRideResponse) Reset() {
	*x = CreateRideResponse{}
	mi := &file_proto_ride_ride_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRideResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRideResponse) ProtoMessage() {}

func (x *CreateRideResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ride_ride_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRideResponse.ProtoReflect.Descriptor instead.
func (*CreateRideResponse) Descriptor() ([]byte, []int) {
	return file_proto_ride_ride_proto_rawDescGZIP(), []int{2}
}

func (x *CreateRideResponse) GetRideId() string {
	if x != nil {
		return x.RideId
	}
	return ""
}

type GetRideRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RideId        string                 `protobuf:"bytes,1,opt,name=ride_id,json=rideId,proto3" json:"ride_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRideRequest) Reset() {
	*x = GetRideRequest{}
	mi := &file_proto_ride_ride_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRideRequest) ProtoMessage() {}

func (x *GetRideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ride_ride_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRideRequest.ProtoReflect.Descriptor instead.
func (*GetRideRequest) Descriptor() ([]byte, []int) {
	return file_proto_ride_ride_proto_rawDescGZIP(), []int{3}
}

func (x *GetRideRequest) GetRideId() string {
	if x != nil {
		return x.RideId
	}
	return ""
}

type GetRideResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RideId        string                 `protobuf:"bytes,1,opt,name=ride_id,json=rideId,proto3" json:"ride_id,omitempty"`
	PassengerId   string                 `protobuf:"bytes,2,opt,name=passenger_id,json=passengerId,proto3" json:"passenger_id,omitempty"`
	DriverId      string                 `protobuf:"bytes,3,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Status        RideStatus             `protobuf:"varint,4,opt,name=status,proto3,enum=ride.RideStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRideResponse) Reset() {
	*x = GetRideResponse{}
	mi := &file_proto_ride_ride_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRideResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRideResponse) ProtoMessage() {}

func (x *GetRideResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ride_ride_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRideResponse.ProtoReflect.Descriptor instead.
func (*GetRideResponse) Descriptor() ([]byte, []int) {
	return file_proto_ride_ride_proto_rawDescGZIP(), []int{4}
}

func (x *GetRideResponse) GetRideId() string {
	if x != nil {
		return x.RideId
	}
	return ""
}

func (x *GetRideResponse) GetPassengerId() string {
	if x != nil {
		return x.PassengerId
	}
	return ""
}

func (x *GetRideResponse) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *GetRideResponse) GetStatus() RideStatus {
	if x != nil {
		return x.Status
	}
	return RideStatus_UNKNOWN
}

type UpdateRideStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RideId        string                 `protobuf:"bytes,1,opt,name=ride_id,json=rideId,proto3" json:"ride_id,omitempty"`
	DriverId      string                 `protobuf:"bytes,2,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Status        RideStatus             `protobuf:"varint,3,opt,name=status,proto3,enum=ride.RideStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRideStatusRequest) Reset() {
	*x = UpdateRideStatusRequest{}
	mi := &file_proto_ride_ride_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRideStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRideStatusRequest) ProtoMessage() {}

func (x *UpdateRideStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ride_ride_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRideStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateRideStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_ride_ride_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateRideStatusRequest) GetRideId() string {
	if x != nil {
		return x.RideId
	}
	return ""
}

func (x *UpdateRideStatusRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *UpdateRideStatusRequest) GetStatus() RideStatus {
	if x != nil {
		return x.Status
	}
	return RideStatus_UNKNOWN
}

type UpdateRideStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRideStatusResponse) Reset() {
	*x = UpdateRideStatusResponse{}
	mi := &file_proto_ride_ride_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRideStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRideStatusResponse) ProtoMessage() {}

func (x *UpdateRideStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ride_ride_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRideStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateRideStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_ride_ride_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateRideStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_ride_ride_proto protoreflect.FileDescriptor

const file_proto_ride_ride_proto_rawDesc = "" +
	"\n" +
	"\x15proto/ride/ride.proto\x12\x04ride\"D\n" +
	"\bLocation\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\"\xaa\x01\n" +
	"\x11CreateRideRequest\x12!\n" +
	"\fpassenger_id\x18\x01 \x01(\tR\vpassengerId\x127\n" +
	"\x0fpickup_location\x18\x02 \x01(\v2\x0e.ride.LocationR\x0epickupLocation\x129\n" +
	"\x10dropoff_location\x18\x03 \x01(\v2\x0e.ride.LocationR\x0fdropoffLocation\"-\n" +
	"\x12CreateRideResponse\x12\x17\n" +
	"\aride_id\x18\x01 \x01(\tR\x06rideId\")\n" +
	"\x0eGetRideRequest\x12\x17\n" +
	"\aride_id\x18\x01 \x01(\tR\x06rideId\"\x94\x01\n" +
	"\x0fGetRideResponse\x12\x17\n" +
	"\aride_id\x18\x01 \x01(\tR\x06rideId\x12!\n" +
	"\fpassenger_id\x18\x02 \x01(\tR\vpassengerId\x12\x1b\n" +
	"\tdriver_id\x18\x03 \x01(\tR\bdriverId\x12(\n" +
	"\x06status\x18\x04 \x01(\x0e2\x10.ride.RideStatusR\x06status\"y\n" +
	"\x17UpdateRideStatusRequest\x12\x17\n" +
	"\aride_id\x18\x01 \x01(\tR\x06rideId\x12\x1b\n" +
	"\tdriver_id\x18\x02 \x01(\tR\bdriverId\x12(\n" +
	"\x06status\x18\x03 \x01(\x0e2\x10.ride.RideStatusR\x06status\"4\n" +
	"\x18UpdateRideStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess*^\n" +
	"\n" +
	"RideStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aCREATED\x10\x01\x12\v\n" +
	"\aMATCHED\x10\x02\x12\v\n" +
	"\aSTARTED\x10\x03\x12\r\n" +
	"\tCOMPLETED\x10\x04\x12\r\n" +
	"\tCANCELLED\x10\x052\xd9\x01\n" +
	"\vRideService\x12?\n" +
	"\n" +
	"CreateRide\x12\x17.ride.CreateRideRequest\x1a\x18.ride.CreateRideResponse\x126\n" +
	"\aGetRide\x12\x14.ride.GetRideRequest\x1a\x15.ride.GetRideResponse\x12Q\n" +
	"\x10UpdateRideStatus\x12\x1d.ride.UpdateRideStatusRequest\x1a\x1e.ride.UpdateRideStatusResponseB/Z-github.com/ngthluu/miniuber/common/proto/rideb\x06proto3"

var (
	file_proto_ride_ride_proto_rawDescOnce sync.Once
	file_proto_ride_ride_proto_rawDescData []byte
)

func file_proto_ride_ride_proto_rawDescGZIP() []byte {
	file_proto_ride_ride_proto_rawDescOnce.Do(func() {
		file_proto_ride_ride_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ride_ride_proto_rawDesc), len(file_proto_ride_ride_proto_rawDesc)))
	})
	return file_proto_ride_ride_proto_rawDescData
}

var file_proto_ride_ride_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_ride_ride_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_ride_ride_proto_goTypes = []any{
	(RideStatus)(0),                  // 0: ride.RideStatus
	(*Location)(nil),                 // 1: ride.Location
	(*CreateRideRequest)(nil),        // 2: ride.CreateRideRequest
	(*CreateRideResponse)(nil),       // 3: ride.CreateRideResponse
	(*GetRideRequest)(nil),           // 4: ride.GetRideRequest
	(*GetRideResponse)(nil),          // 5: ride.GetRideResponse
	(*UpdateRideStatusRequest)(nil),  // 6: ride.UpdateRideStatusRequest
	(*UpdateRideStatusResponse)(nil), // 7: ride.UpdateRideStatusResponse
}
var file_proto_ride_ride_proto_depIdxs = []int32{
	1, // 0: ride.CreateRideRequest.pickup_location:type_name -> ride.Location
	1, // 1: ride.CreateRideRequest.dropoff_location:type_name -> ride.Location
	0, // 2: ride.GetRideResponse.status:type_name -> ride.RideStatus
	0, // 3: ride.UpdateRideStatusRequest.status:type_name -> ride.RideStatus
	2, // 4: ride.RideService.CreateRide:input_type -> ride.CreateRideRequest
	4, // 5: ride.RideService.GetRide:input_type -> ride.GetRideRequest
	6, // 6: ride.RideService.UpdateRideStatus:input_type -> ride.UpdateRideStatusRequest
	3, // 7: ride.RideService.CreateRide:output_type -> ride.CreateRideResponse
	5, // 8: ride.RideService.GetRide:output_type -> ride.GetRideResponse
	7, // 9: ride.RideService.UpdateRideStatus:output_type -> ride.UpdateRideStatusResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_ride_ride_proto_init() }
func file_proto_ride_ride_proto_init() {
	if File_proto_ride_ride_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ride_ride_proto_rawDesc), len(file_proto_ride_ride_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ride_ride_proto_goTypes,
		DependencyIndexes: file_proto_ride_ride_proto_depIdxs,
		EnumInfos:         file_proto_ride_ride_proto_enumTypes,
		MessageInfos:      file_proto_ride_ride_proto_msgTypes,
	}.Build()
	File_proto_ride_ride_proto = out.File
	file_proto_ride_ride_proto_goTypes = nil
	file_proto_ride_ride_proto_depIdxs = nil
}
