// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/driver/driver.proto

package driver

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDriverProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDriverProfileRequest) Reset() {
	*x = GetDriverProfileRequest{}
	mi := &file_proto_driver_driver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriverProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriverProfileRequest) ProtoMessage() {}

func (x *GetDriverProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_driver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriverProfileRequest.ProtoReflect.Descriptor instead.
func (*GetDriverProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_driver_driver_proto_rawDescGZIP(), []int{0}
}

func (x *GetDriverProfileRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

type GetDriverProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	VehicleModel  string                 `protobuf:"bytes,3,opt,name=vehicle_model,json=vehicleModel,proto3" json:"vehicle_model,omitempty"`
	VehiclePlate  string                 `protobuf:"bytes,4,opt,name=vehicle_plate,json=vehiclePlate,proto3" json:"vehicle_plate,omitempty"`
	Rating        float64                `protobuf:"fixed64,5,opt,name=rating,proto3" json:"rating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDriverProfileResponse) Reset() {
	*x = GetDriverProfileResponse{}
	mi := &file_proto_driver_driver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriverProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriverProfileResponse) ProtoMessage() {}

func (x *GetDriverProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_driver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriverProfileResponse.ProtoReflect.Descriptor instead.
func (*GetDriverProfileResponse) Descriptor() ([]byte, []int) {
	return file_proto_driver_driver_proto_rawDescGZIP(), []int{1}
}

func (x *GetDriverProfileResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetDriverProfileResponse) GetVehicleModel() string {
	if x != nil {
		return x.VehicleModel
	}
	return ""
}

func (x *GetDriverProfileResponse) GetVehiclePlate() string {
	if x != nil {
		return x.VehiclePlate
	}
	return ""
}

func (x *GetDriverProfileResponse) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

type ToggleAvailabilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	IsAvailable   bool                   `protobuf:"varint,2,opt,name=is_available,json=isAvailable,proto3" json:"is_available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleAvailabilityRequest) Reset() {
	*x = ToggleAvailabilityRequest{}
	mi := &file_proto_driver_driver_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleAvailabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleAvailabilityRequest) ProtoMessage() {}

func (x *ToggleAvailabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_driver_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleAvailabilityRequest.ProtoReflect.Descriptor instead.
func (*ToggleAvailabilityRequest) Descriptor() ([]byte, []int) {
	return file_proto_driver_driver_proto_rawDescGZIP(), []int{2}
}

func (x *ToggleAvailabilityRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *ToggleAvailabilityRequest) GetIsAvailable() bool {
	if x != nil {
		return x.IsAvailable
	}
	return false
}

type ToggleAvailabilityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleAvailabilityResponse) Reset() {
	*x = ToggleAvailabilityResponse{}
	mi := &file_proto_driver_driver_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleAvailabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleAvailabilityResponse) ProtoMessage() {}

func (x *ToggleAvailabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_driver_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleAvailabilityResponse.ProtoReflect.Descriptor instead.
func (*ToggleAvailabilityResponse) Descriptor() ([]byte, []int) {
	return file_proto_driver_driver_proto_rawDescGZIP(), []int{3}
}

func (x *ToggleAvailabilityResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_driver_driver_proto protoreflect.FileDescriptor

const file_proto_driver_driver_proto_rawDesc = "" +
	"\n" +
	"\x19proto/driver/driver.proto\x12\x06driver\"6\n" +
	"\x17GetDriverProfileRequest\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\"\x90\x01\n" +
	"\x18GetDriverProfileResponse\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12#\n" +
	"\rvehicle_model\x18\x03 \x01(\tR\fvehicleModel\x12#\n" +
	"\rvehicle_plate\x18\x04 \x01(\tR\fvehiclePlate\x12\x16\n" +
	"\x06rating\x18\x05 \x01(\x01R\x06rating\"[\n" +
	"\x19ToggleAvailabilityRequest\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\x12!\n" +
	"\fis_available\x18\x02 \x01(\bR\visAvailable\"6\n" +
	"\x1aToggleAvailabilityResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xc3\x01\n" +
	"\rDriverService\x12U\n" +
	"\x10GetDriverProfile\x12\x1f.driver.GetDriverProfileRequest\x1a .driver.GetDriverProfileResponse\x12[\n" +
	"\x12ToggleAvailability\x12!.driver.ToggleAvailabilityRequest\x1a\".driver.ToggleAvailabilityResponseB1Z/github.com/ngthluu/miniuber/common/proto/driverb\x06proto3"

var (
	file_proto_driver_driver_proto_rawDescOnce sync.Once
	file_proto_driver_driver_proto_rawDescData []byte
)

func file_proto_driver_driver_proto_rawDescGZIP() []byte {
	file_proto_driver_driver_proto_rawDescOnce.Do(func() {
		file_proto_driver_driver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_driver_driver_proto_rawDesc), len(file_proto_driver_driver_proto_rawDesc)))
	})
	return file_proto_driver_driver_proto_rawDescData
}

var file_proto_driver_driver_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_driver_driver_proto_goTypes = []any{
	(*GetDriverProfileRequest)(nil),    // 0: driver.GetDriverProfileRequest
	(*GetDriverProfileResponse)(nil),   // 1: driver.GetDriverProfileResponse
	(*ToggleAvailabilityRequest)(nil),  // 2: driver.ToggleAvailabilityRequest
	(*ToggleAvailabilityResponse)(nil), // 3: driver.ToggleAvailabilityResponse
}
var file_proto_driver_driver_proto_depIdxs = []int32{
	0, // 0: driver.DriverService.GetDriverProfile:input_type -> driver.GetDriverProfileRequest
	2, // 1: driver.DriverService.ToggleAvailability:input_type -> driver.ToggleAvailabilityRequest
	1, // 2: driver.DriverService.GetDriverProfile:output_type -> driver.GetDriverProfileResponse
	3, // 3: driver.DriverService.ToggleAvailability:output_type -> driver.ToggleAvailabilityResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_driver_driver_proto_init() }
func file_proto_driver_driver_proto_init() {
	if File_proto_driver_driver_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_driver_driver_proto_rawDesc), len(file_proto_driver_driver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_driver_driver_proto_goTypes,
		DependencyIndexes: file_proto_driver_driver_proto_depIdxs,
		MessageInfos:      file_proto_driver_driver_proto_msgTypes,
	}.Build()
	File_proto_driver_driver_proto = out.File
	file_proto_driver_driver_proto_goTypes = nil
	file_proto_driver_driver_proto_depIdxs = nil
}
